version: "3.7"

services:
  api:
    build: 
      context: .
      dockerfile: ./.docker/ApiDockerfile
    container_name: api
    ports: 
      - 3000:3000
    volumes:
    - ./api:/root/api
    - gems:/usr/local/bundle
    depends_on:
      - pgdb
    command: ["rails","server"]
    environment:
      - CLIENT_URL=http://localhost
      - GITHUB_CLIENT_ID=a86bc65853ae65d3be52
    secrets:
      - github_client_secret
      - jwt_secret
  client:
    build:
      context: .
      dockerfile: ./.docker/ClientDockerfile
    container_name: client
    ports:
      - 80:3000
      - 35729:35729
    volumes:
      - ./client:/root/client
    command: ["yarn","start"]
  pgdb:
    image: postgres:10-alpine
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_PASSWORD: secretword
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  gems:
  node_modules:
  pgdata:
secrets:
  github_client_secret:
    file: ./.docker/.secrets/github_client_secret.txt
  jwt_secret:
    file: ./.docker/.secrets/jwt_secret.txt