version: "3.7"

services:
  api:
    build: 
      context: .
      dockerfile: ./.docker/Dockerfile
      target: api-dev
    container_name: api
    ports: 
      - 3000:3000
    volumes:
    - ./api:/root/api
    - gems:/usr/local/bundle
    depends_on:
      - pgdb
    command: ["rails","server"]
    environment:
      - CLIENT_URL=http://localhost
    secrets:
      - pg_user
      - pg_password
      - pg_database
      - github_client_id
      - github_client_secret
      - jwt_secret
  client:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: client-dev
    container_name: client
    ports:
      - 80:3000
      - 35729:35729
    volumes:
      - ./client:/root/client
    command: ["yarn","start"]
  pgdb:
    image: postgres:10-alpine
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_PASSWORD: secretword
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  gems:
  node_modules:
  pgdata:
secrets:
  pg_user:
    file: ./.docker/.secrets/pg_user.txt
  pg_password:
    file: ./.docker/.secrets/pg_password.txt
  pg_database:
    file: ./.docker/.secrets/pg_database.txt
  github_client_id:
    file: ./.docker/.secrets/github_client_secret.txt
  github_client_secret:
    file: ./.docker/.secrets/github_client_secret.txt
  jwt_secret:
    file: ./.docker/.secrets/jwt_secret.txt