# PRODUCTION COMPOSE FILE
version: '3.7'

services:
  image: 
  app:
    depends_on: pgdb
  pgdb:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      POSTGRES_DB_FILE: /run/secrets/pg_database
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - pg_password
      - pg_user
      - pg_database
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  # adminer: 
  #   image: adminer 
  #   ports: 
  #     - 8080:8080
volumes:
  pgdata:
    external: true
secrets:
  pg_user:
    external: true
  pg_password:
    external: true
  pg_database:
    external: true